/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios;

import Pedido.ActualizarPedido;
import Pedido.ActualizarPedidoV2;
import Pedido.ImprimirPedido;
import Pedido.RecibidoPedido;
import Pedido.RecibidoPedidoV2;
import Pedido.Solicitud;
import java.awt.BorderLayout;

/**
 *
 * @author it
 */
public class Pedido extends javax.swing.JPanel {

    /**
     * Creates new form Pedido
     */
    public Pedido() {
        initComponents();
        String texto1 = "<html><center><body>NUEVO<br>PEDIDO</body></center></html>";
        NUEVO.setText(texto1);
        String texto2 = "<html><center><body>ACTUALIZAR<br>PEDIDO</body></center></html>";
        ACTUALIZAR.setText(texto2);
        String texto3 = "<html><center><body>CANTIDAD<br>RECIBIDA</body></center></html>";
        RECIBIDO.setText(texto3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new ClassAngels.PanelRound();
        NUEVO = new javax.swing.JLabel();
        panelRound2 = new ClassAngels.PanelRound();
        ACTUALIZAR = new javax.swing.JLabel();
        panelRound3 = new ClassAngels.PanelRound();
        RECIBIDO = new javax.swing.JLabel();
        panelRound4 = new ClassAngels.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        PanelPedidos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        panelRound1.setBackground(new java.awt.Color(255, 255, 153));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        NUEVO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NUEVO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUEVO.setText("NUEVO PEDIDO");
        NUEVO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUEVOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NUEVO, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NUEVO, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        panelRound2.setBackground(new java.awt.Color(255, 255, 153));
        panelRound2.setPreferredSize(new java.awt.Dimension(124, 55));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        ACTUALIZAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ACTUALIZAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ACTUALIZAR.setText("ACTUALIZAR PEDIDO");
        ACTUALIZAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACTUALIZARMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ACTUALIZAR, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        panelRound3.setBackground(new java.awt.Color(255, 255, 153));
        panelRound3.setPreferredSize(new java.awt.Dimension(124, 55));
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);

        RECIBIDO.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RECIBIDO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RECIBIDO.setText("CANTIDAD RECIBIDA");
        RECIBIDO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RECIBIDOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RECIBIDO, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RECIBIDO, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        panelRound4.setBackground(new java.awt.Color(255, 255, 153));
        panelRound4.setPreferredSize(new java.awt.Dimension(124, 55));
        panelRound4.setRoundBottomLeft(20);
        panelRound4.setRoundBottomRight(20);
        panelRound4.setRoundTopLeft(20);
        panelRound4.setRoundTopRight(20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("IMPRIMIR");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(800, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelPedidos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelPedidosLayout = new javax.swing.GroupLayout(PanelPedidos);
        PanelPedidos.setLayout(PanelPedidosLayout);
        PanelPedidosLayout.setHorizontalGroup(
            PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelPedidosLayout.setVerticalGroup(
            PanelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NUEVOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUEVOMouseClicked
    Solicitud op2 = new Solicitud();
    op2.setSize(1315, 500); 
    op2.setLocation(0, 0);
    PanelPedidos.removeAll();
    PanelPedidos.add(op2,BorderLayout.CENTER);
    PanelPedidos.revalidate();
    PanelPedidos.repaint();
    }//GEN-LAST:event_NUEVOMouseClicked

    private void ACTUALIZARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACTUALIZARMouseClicked
    ActualizarPedidoV2 op2 = new ActualizarPedidoV2();
    op2.setSize(1315, 500); 
    op2.setLocation(0, 0);
    PanelPedidos.removeAll();
    PanelPedidos.add(op2,BorderLayout.CENTER);
    PanelPedidos.revalidate();
    PanelPedidos.repaint();
    }//GEN-LAST:event_ACTUALIZARMouseClicked

    private void RECIBIDOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RECIBIDOMouseClicked
    RecibidoPedidoV2 op2 = new RecibidoPedidoV2();
    op2.setSize(1320, 500); 
    op2.setLocation(0, 0);
    PanelPedidos.removeAll();
    PanelPedidos.add(op2,BorderLayout.CENTER);
    PanelPedidos.revalidate();
    PanelPedidos.repaint();
    }//GEN-LAST:event_RECIBIDOMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    ImprimirPedido op2 = new ImprimirPedido();
    op2.setSize(1320, 500); 
    op2.setLocation(0, 0);
    PanelPedidos.removeAll();
    PanelPedidos.add(op2,BorderLayout.CENTER);
    PanelPedidos.revalidate();
    PanelPedidos.repaint();
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACTUALIZAR;
    private javax.swing.JLabel NUEVO;
    private javax.swing.JPanel PanelPedidos;
    private javax.swing.JLabel RECIBIDO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private ClassAngels.PanelRound panelRound1;
    private ClassAngels.PanelRound panelRound2;
    private ClassAngels.PanelRound panelRound3;
    private ClassAngels.PanelRound panelRound4;
    // End of variables declaration//GEN-END:variables
}
