/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pedido;

import ClasesAngels.BDConexion_server;
import ClassAngels.TextAreaRenderer;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author it
 */
public class ImprimirPedido extends javax.swing.JPanel {

    int id_pedido;
    int id_pedidoRecibidos;
    /**
     * Creates new form Solicitud
     */
    public ImprimirPedido() {
        initComponents();
        ListarPedidos();
        ListarPedidosRecibidos();
    }

    private void imprimir() {

        id_pedido = (Integer.parseInt(String.valueOf(TablePedidos.getModel().getValueAt(TablePedidos.getSelectedRow(), 0))));

        BDConexion_server con = new BDConexion_server();
        Connection conexion = con.getConexion();
        try {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObjectFromFile("C:\\Reportes\\ANGELS\\ReportePedidos.jasper");
            Map parametros = new HashMap();
            parametros.put("ID_PEDIDO", id_pedido);
            JasperPrint print = JasperFillManager.fillReport(jasperReport, parametros, conexion);
            JasperPrintManager.printReport(print, true);
        } catch (JRException e) {
            System.out.println("F" + e);
            JOptionPane.showMessageDialog(null, "ERROR EJECUTAR REPORTES =  " + e);
        }
    }
    
     private void imprimirRecibidos() {

        id_pedido = (Integer.parseInt(String.valueOf(TablePedidosRecibidos.getModel().getValueAt(TablePedidosRecibidos.getSelectedRow(), 0))));

        BDConexion_server con = new BDConexion_server();
        Connection conexion = con.getConexion();
        try {
            JasperReport jasperReport = (JasperReport) JRLoader.loadObjectFromFile("C:\\Reportes\\ANGELS\\ReportePedidosRecibido.jasper");
            Map parametros = new HashMap();
            parametros.put("ID_PEDIDO", id_pedido);
            JasperPrint print = JasperFillManager.fillReport(jasperReport, parametros, conexion);
            JasperPrintManager.printReport(print, true);
        } catch (JRException e) {
            System.out.println("F" + e);
            JOptionPane.showMessageDialog(null, "ERROR EJECUTAR REPORTES =  " + e);
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablePedidos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePedidosRecibidos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        TablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No.", "Fecha"
            }
        ));
        TablePedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePedidos);

        TablePedidosRecibidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No.", "Fecha"
            }
        ));
        TablePedidosRecibidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePedidosRecibidosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablePedidosRecibidos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEDIDOS PENDIENTES DE RECIBIR");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PEDIDOS RECIBIDOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablePedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePedidosMouseClicked
        if (evt.getClickCount() > 1) {

            imprimir();
        }

    }//GEN-LAST:event_TablePedidosMouseClicked

    private void TablePedidosRecibidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePedidosRecibidosMouseClicked
         if (evt.getClickCount() > 1) {

            imprimirRecibidos();
        }
    }//GEN-LAST:event_TablePedidosRecibidosMouseClicked

    private void ListarPedidos() {

        ArrayList<ClassProductos> result = BDIngresosConsultas.ListarPedidosImprimir();
        RecargarTablaPedidos(result);
    }

    private void RecargarTablaPedidos(ArrayList<ClassProductos> list) {
        Object[][] datos = new Object[list.size()][2];
        int i = 0;
        for (ClassProductos t : list) {
            datos[i][0] = t.getId_pedido();
            datos[i][1] = t.getFechain();
            i++;
        }
        TablePedidos.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    "No.", "FECHA"
                }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        TablePedidos.getColumnModel().getColumn(1).setCellRenderer(new TextAreaRenderer());
        TableColumn columna1 = TablePedidos.getColumn("No.");
        columna1.setPreferredWidth(-20);
        TableColumn columna2 = TablePedidos.getColumn("FECHA");
        columna2.setPreferredWidth(255);

    }
    
    private void ListarPedidosRecibidos() {

        ArrayList<ClassProductos> result = BDIngresosConsultas.ListarPedidosImprimirRecibidos();
        RecargarTablaPedidosRecibidos(result);
    }

    private void RecargarTablaPedidosRecibidos(ArrayList<ClassProductos> list) {
        Object[][] datos = new Object[list.size()][2];
        int i = 0;
        for (ClassProductos t : list) {
            datos[i][0] = t.getId_pedido();
            datos[i][1] = t.getFechain();
            i++;
        }
        TablePedidosRecibidos.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    "No.", "FECHA"
                }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        TablePedidosRecibidos.getColumnModel().getColumn(1).setCellRenderer(new TextAreaRenderer());
        TableColumn columna1 = TablePedidosRecibidos.getColumn("No.");
        columna1.setPreferredWidth(-20);
        TableColumn columna2 = TablePedidosRecibidos.getColumn("FECHA");
        columna2.setPreferredWidth(255);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePedidos;
    private javax.swing.JTable TablePedidosRecibidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
