/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pedido;

import ClassAngels.TextAreaRenderer;
import java.util.ArrayList;
import javax.swing.table.TableColumn;

/**
 *
 * @author it
 */
public class ImprimirPedido extends javax.swing.JPanel {

    /**
     * Creates new form Solicitud
     */
    public ImprimirPedido() {
        initComponents();
        ListarPedidos();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablePedidos = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 255));

        TablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No.", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(TablePedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(797, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

     private void ListarPedidos(){
  
        ArrayList<ClassProductos> result = BDIngresosConsultas.ListarPedidosImprimir();
        RecargarTablaPedidos(result);  
    }
     private void RecargarTablaPedidos(ArrayList<ClassProductos> list) {
              Object[][] datos = new Object[list.size()][2];
              int i = 0;
              for(ClassProductos t : list)
              {
                  datos[i][0] = t.getId_pedido();
                  datos[i][1] = t.getFechain();
                  i++;
              }    
             TablePedidos.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                "No.","FECHA"
             })
             {  
                 @Override
                 public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TablePedidos.getColumnModel().getColumn(1).setCellRenderer(new TextAreaRenderer());
             TableColumn columna1 = TablePedidos.getColumn("No.");
             columna1.setPreferredWidth(-20);
             TableColumn columna2 = TablePedidos.getColumn("FECHA");
             columna2.setPreferredWidth(255);
           
     } 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePedidos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
